CORUSANT


PLANET:       Coruscant
TYPE:         Terrestrial planet, City-planet
CLIMATE:      Temperate (artificially regulated by orbital mirrors)
MOONS:        4 moons (Centrax, Hvivia, Viszunt, Kuan)
TERRAIN:      Fully urbanized surface, multi-level urban development
LOCATION:     Galactic Core, Coruscant sector, Coruscant system
NATIVE RACES: Humans, thousands of other species
ALLIANCE:     Galactic Republic (formerly), Galactic Empire (formerly), New Republic (formerly), Galactic Union (currently)
LOCATIONS:    Jedi Temple, Senate Building, Imperial Palace, Lower City Levels, Manarai Mountains, Western Sea

DESCRIPTION:

Coruscant is a glittering city-planet located at the heart of the galaxy. For millennia, it served as a political, cultural, and financial center, where decisions were made affecting the fates of trillions of sentient beings. The planet's name derives from the constant play of light on its surface when viewed from space, reminiscent of the sparkle of Coruscant's precious stones.

Coruscant's surface is completely hidden beneath a vast, multi-level metropolis that has grown over thousands of generations. Gigantic buildings, some reaching 6 kilometers in height, cover every square meter of land, burying all natural landscapes—mountains, seas, and oceans. Water is stored in vast underground reservoirs, and the only open body of water remains the artificial Western Sea, home to floating islands for recreation.

The galactic city is divided into several thousand squares and sectors. The upper levels are occupied by government offices, financial centers, and the penthouses of the wealthiest elite. Here, the air undergoes multi-stage purification, and traffic is strictly regulated by automated highways.

The lower levels are a bleak world, deprived of sunlight for centuries. There, under artificial light, live the poorest strata of the population, where crime and decay reign. Even deeper, in the foundations of the buildings, lie forgotten levels with a barely breathable atmosphere, home to mutants, scavengers, and dangerous creatures like the Kton.

The planet's climate is maintained by a system of orbital mirrors that redistribute energy from Coruscant Prime's star, as the planet's natural orbit is too distant for comfortable human habitation. Thousands of atmospheric regenerators purify the air of the colossal waste generated by a trillion people.

KEY LOCATIONS:

- Jedi Temple: A monumental building towering over the capital city, it served as the headquarters of the Jedi Order for millennia.
- Senate Building: A vast domed complex that housed the Galactic Senate, the Republic's main legislative body.
- Imperial Palace: A former Jedi Temple, converted by Emperor Palpatine into his residence. Located at the foot of the Manarai Mountains.
- Manarai Mountains: One of the planet's few remaining natural landscapes, this twin mountain peak is home to the Imperial Palace and Monument Plaza.
- Lower City Levels: A multi-story labyrinth of tunnels and levels where sunlight never penetrates. Home to the poor, criminals, and social outcasts.
- Western Sea: An artificial body of water with floating islands, created for recreation and relaxation.
