name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to Workshop
        uses: MagicFoxGames/gmod-addon-upload@main
        with:
          id: 3584451844
          changelog: "${{ github.event.release.body }}"
          steam_tfaseed: ${{ secrets.STEAM_TFASEED }}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
